spring:
  thymeleaf:
    cache:false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  #带cj是8.x版本不带是5.7版本
    url: jdbc:mysql://localhost:3306/xxxxxxxx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxxxx
    hikari:
      #连接池名称
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接数存活最大时间，默认600000(10分钟)
      idle-timeout: 18000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      #连接超时时间
      connection-timeout: 30000
      #心跳机制，测试连接是否可用的查询语句
      connection-test-query: select 1
  redis:
    host: xxxxxxxx
    port: 6379
    #默认操作的数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1，默认不会去等待
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  rabbitmq:
    #服务器
    host: xxxxxxxx
    username: admin  #guest不行
    password: 123456
    virtual-host: /
    #15672是web访问端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #最大重试次数，默认3次
        max-attempts: 3
        #最大重试间隔，默认1000ms
        max-interval: 1000ms
        #重试的间隔乘数，例如参数为2.0，则第一次等1s，第二次等2s，第三次4s
        multiplier: 1


mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名
  type-aliases-package: com.cug.myseckill.pojo

# MyBatis SQL打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.cug.myseckill.mapper: debug

